food_estimation_task:
  description: >
    Analyze the provided image at {image_fs_location} to identify all visible food items or raw foods.
    For each item, determine a descriptive name and estimate its weight in grams.
    Ensure the names are suitable for recipe lookup and the weight estimations are realistic.
    If confidence in any item's identification or quantity is below 90%, repeat the analysis.
    If there is a food product - list it, do not try to find out/guess its ingredients.
  expected_output: >
    A markdown-formatted list of all identified food items in the format: 
    - <name>: <weight in grams> — confidence: <confidence level>%
    Only include results where confidence is 90% or higher.
  agent: vision_food_estimator


# reporting_task:
#   description: >
#     Review the context you got and expand each topic into a full section for a report.
#     Make sure the report is detailed and contains any and all relevant information.
#   expected_output: >
#     A fully fledged report with the main topics, each with a full section of information.
#     Formatted as markdown without '```'
#   agent: reporting_analyst
